#!/bin/bash
# camcap.sh: installs a crontab task list for capturing online video streams using
#            single_camcap.sh.
# Authors: Vahid Bastani
#
# Dependencies: crontab
# Syntax: ./camcap.sh [camcap_file]
#   camcap_file: the configuration file for video capturing scheduler
#                (default: camcapfile)

# ignore * character as special shell character
GLOBIGNORE="*"

filename="camcapfile"
if [ -z "$1" ]; then
   echo "installing default $filename."
else
   filename=$1
fi

echo "# This is a cron file generated by camcap" > crontabfile

line_num=0
while read -r line
do
   ((line_num++))
   #skip empty line
   len=${#line}
   if (( len == 0 )); then
      continue
   fi
   #proceed to next line if the line is a comment
   first_char=${line:0:1}
   if [ $first_char == "#" ] ; then
     continue
   fi

   # divide the line with white-space delimiter
   IFS=' ' read -r -a line_arr <<< $line
   a_len=0
   for x in "${line_arr[@]}"
   do
      (( a_len++ ))
   done
   if [ $a_len != "8" ]; then
      echo "syntax error at line $line_num"
      exit 1
   fi
   cron_command="${line_arr[1]} ${line_arr[2]} ${line_arr[3]} ${line_arr[4]} ${line_arr[5]} $PWD/single_camcap.sh ${line_arr[6]} ${line_arr[0]} ${line_arr[7]}"

   echo "$cron_command" >> crontabfile

done < "$filename"

#install crontabfile
crontab crontabfile
